### PR TITLE
Added support for CASE_SENSITIVE setting

### LINKED ISSUE #302: Feature request: Ability to set case sensitivity in Helix Core
### Use case

Helix Core `p4d` has a list of startup flags that can be passed in to achieve different things (a full list can be found [here](https://www.perforce.com/manuals/p4sag/Content/P4SAG/appendix.p4d.html) ). 

For example, both Windows and UGS require the server to be run in case insensitive mode, which is the `-C1` startup flag.  

### Solution/User Experience

Add some ability to set the case sensitivity in the `helix-core` module on setup.
### Alternative solutions

_No response_

### PR DESCRIPTION
**Pull request by keith-miller**
resolves #302

**Issue number:**

### Changes

Added support for CASE_SENSITIVE setting

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ X] I have performed a self-review of this change
* [ X] Changes have been tested
* [ ] Changes are documented

<details>
<summary>Is this a breaking change?</summary>

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created might not be successful.

### CODE REVIEW

**Comment by keith-miller** [comment]
This is my first pass @henrykie which works, but I'm sure you will want to make the wording better :)

**Comment by henrykie** [comment]
@GrzesiekO take a look...

**Comment by henrykie** [comment]
@keith-miller this looks great to me. If it works for you then I'll let @GrzesiekO review - he may want to use this approach for now. We've been going back and forth on replacing this bash script entirely eventually, and as new requests for modifications come in we're leaning more and more that way.

We still need to set unicode mode. My understanding is you can do that against the server once it is already booted? We will still want to consider doing it by default.

**Comment by keith-miller** [comment]
@henrykie that's correct. We were able to enable unicode support after the fact and are unblocked using this code.

**Comment by GrzesiekO** [comment]
Seen the changes need to test it but seems like a quick fix following current pattern. Thank you @keith-miller!

**Review by GrzesiekO — APPROVED** [review]
All changes with current convention. Adds case sensitivity option for p4d. 
Approving.

**Review by henrykie — APPROVED** [review]

**Pull request merged**
